# Default values for webappdeployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
#Start  custom attributes
namespace: dev-aks-sinhuiapp
env:
  "ASPNETCORE_ENVIRONMENT": "Development"
  "ASPNETCORE_FORWARDEDHEADERS_ENABLED": "true"
#End Custom attributes
labels:
    fnf_app_id1: "1944"
    fnf_app_name: "SalesinHere"
    fnf_businessservice_id: "1944.DEV"
    fnf_costcenter: "01400.901771.160"
    fnf_datacenter: "Azure"
    fnf_lineofbusiness_id: "1"
    fnf_parenthosting_id: "2.1"
image:
  repository: ccopaksacrdevapp.azurecr.io/sinh/sinhuiapp
  pullPolicy: IfNotPresent
  tag: "v0.1"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: "sinhuiapp"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  runAsUser: 1019
  allowPrivilegeEscalation: false

service:
  type: ClusterIP
  port: 8080
 
ingress:
  enabled: true
  className: ""
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true" 
    nginx.ingress.kubernetes.io/secure-backends: "true"    
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
 
    #new changes for testing
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "sinhuiapp-cookie"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/affinity-mode: persistent
    nginx.ingress.kubernetes.io/session-cookie-hash: sha1

    #new changes for testing aks blazor websocket issue fix
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    # nginx.ingress.kubernetes.io/upgrade: "websocket"
    # nginx.ingress.kubernetes.io/connection-proxy-header: "upgrade"

    #new changes suggested by MS team to debug websocket issue 
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/configuration-snippet: |  
      proxy_set_header Upgrade $http_upgrade;  
      proxy_set_header Connection "upgrade";  
      proxy_http_version 1.1;  
      proxy_set_header Host $host;  
      proxy_cache_bypass $http_upgrade;  
      proxy_set_header X-Forwarded-Host $http_host;  
      proxy_set_header X-Forwarded-Proto $scheme;  
      proxy_set_header X-Forwarded-For $remote_addr;  

  hosts:
     - host: ui-dev.salesnavigator.fnf.com
       paths:
         - path: /
           pathType: Prefix 
  tls: 
   - secretName: ui-dev.salesnavigator.fnf.com
     hosts:
       - ui-dev.salesnavigator.fnf.com

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: "750m"
    memory: 750Mi
  requests:
    cpu: 500m
    memory: 500Mi 
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
